name: Build and Publish image to Docker Hub
on:
  push:
    branches:
      - main
    paths:
      - 'api/Dockerfile'
      - 'front-end-nextjs/Dockerfile'

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.KKRISH7 }}" | docker login -u "kkrish7" --password-stdin

      - name: Build Docker Images
        run: |
          docker build ./api/ -t kkrish7/devops-qr-code-backend:latest
          docker build ./front-end-nextjs/ -t kkrish7/devops-qr-code-frontend:latest

      - name: Push Images to Docker Hub
        run: |
          docker push kkrish7/devops-qr-code-backend:latest
          docker push kkrish7/devops-qr-code-frontend:latest
